//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectoSystem.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class votinglivedbEntities : DbContext
    {
        public votinglivedbEntities()
            : base("name=votinglivedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tacademicyear> tacademicyears { get; set; }
        public virtual DbSet<tclass> tclasses { get; set; }
        public virtual DbSet<tclasssection> tclasssections { get; set; }
        public virtual DbSet<tgender> tgenders { get; set; }
        public virtual DbSet<thousedesignation> thousedesignations { get; set; }
        public virtual DbSet<thouseelection> thouseelections { get; set; }
        public virtual DbSet<thousenomination> thousenominations { get; set; }
        public virtual DbSet<thous> thouses { get; set; }
        public virtual DbSet<trole> troles { get; set; }
        public virtual DbSet<tsection> tsections { get; set; }
        public virtual DbSet<tsenatedesignation> tsenatedesignations { get; set; }
        public virtual DbSet<tsenateelection> tsenateelections { get; set; }
        public virtual DbSet<tsenatenomination> tsenatenominations { get; set; }
        public virtual DbSet<tstaff> tstaffs { get; set; }
        public virtual DbSet<tstudent> tstudents { get; set; }
        public virtual DbSet<tvotedstudent> tvotedstudents { get; set; }
        public virtual DbSet<tcolumncode> tcolumncodes { get; set; }
        public virtual DbSet<tewsmessage> tewsmessages { get; set; }
        public virtual DbSet<tewsmessageseverity> tewsmessageseverities { get; set; }
        public virtual DbSet<vlogin> vlogins { get; set; }
    }
}
