//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectoSystem.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tclass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tclass()
        {
            this.tclasssections = new HashSet<tclasssection>();
        }
    
        public int Cls_Id { get; set; }
        public string Cls_Name { get; set; }
        public string Cls_DisplayName { get; set; }
        public Nullable<bool> Cls_IsDeleted { get; set; }
        public Nullable<System.DateTime> Cls_DeletedDate { get; set; }
        public Nullable<int> Cls_DeletedBy { get; set; }
        public Nullable<System.DateTime> Cls_LastUpdatedDate { get; set; }
        public Nullable<int> Cls_LastUpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tclasssection> tclasssections { get; set; }
    }
}
