//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectoSystem.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class thous
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public thous()
        {
            this.thousedesignations = new HashSet<thousedesignation>();
            this.thousenominations = new HashSet<thousenomination>();
            this.tstudents = new HashSet<tstudent>();
        }
    
        public int Hus_Id { get; set; }
        public string Hus_Name { get; set; }
        public string Hus_Description { get; set; }
        public string Hus_HouseCode { get; set; }
        public Nullable<bool> Hus_IsDeleted { get; set; }
        public Nullable<System.DateTime> Hus_DeletedDate { get; set; }
        public Nullable<int> Hus_DeletedBy { get; set; }
        public Nullable<System.DateTime> Hus_LastUpdatedDate { get; set; }
        public Nullable<int> Hus_LastUpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<thousedesignation> thousedesignations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<thousenomination> thousenominations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tstudent> tstudents { get; set; }
    }
}
