//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectoSystem.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tsection()
        {
            this.tclasssections = new HashSet<tclasssection>();
        }
    
        public int Sec_Id { get; set; }
        public string Sec_Name { get; set; }
        public string Sec_DisplayName { get; set; }
        public Nullable<bool> Sec_IsDeleted { get; set; }
        public Nullable<System.DateTime> Sec_DeletedDate { get; set; }
        public Nullable<int> Sec_DeletedBy { get; set; }
        public Nullable<System.DateTime> Sec_LastUpdatedDate { get; set; }
        public Nullable<int> Sec_LastUpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tclasssection> tclasssections { get; set; }
    }
}
