//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectoSystem.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tstaff
    {
        public int Stf_UserId { get; set; }
        public string Stf_FirstName { get; set; }
        public string Stf_MiddleName { get; set; }
        public string Stf_LastName { get; set; }
        public Nullable<System.DateTime> Stf_DoB { get; set; }
        public string Stf_EmailId { get; set; }
        public string Stf_ContactNo { get; set; }
        public Nullable<int> Stf_GenderId { get; set; }
        public Nullable<int> Stf_AddressId { get; set; }
        public Nullable<bool> Stf_IsCandidate { get; set; }
        public Nullable<int> Stf_RoleId { get; set; }
        public string Stf_Password { get; set; }
        public Nullable<System.DateTime> Stf_CreatedDate { get; set; }
        public Nullable<int> Stf_CreatedBy { get; set; }
        public Nullable<bool> Stf_IsDeleted { get; set; }
        public Nullable<System.DateTime> Stf_DeletedDate { get; set; }
        public Nullable<int> Stf_Usr_DeletedBy { get; set; }
        public Nullable<System.DateTime> Stf_LastUpdatedDate { get; set; }
        public Nullable<int> Stf_LastUpdatedBy { get; set; }
    
        public virtual trole trole { get; set; }
    }
}
